### ISSUE TITLE
How do I configure?

### ISSUE THREAD

**Issue by jdlrobson** [WikiMANNia/MediaWiki-Skins-with-Advertisements#1]
None of the wg config variables mentioned in https://github.com/WikiMANNia/MediaWiki-Skins-with-Advertisements/blob/master/README.md seem to work. Is there a dependency that should be installed?

**Comment by WikiMANNia** [comment]
Read first!
**Note 1:** The top banner ad is displayed randomly alternating with the sitenotice.
**Note 2:** The ads in the sidebar will not shown until you placed the markers _* AD1_ and _* AD2_ in the [MediaWiki:Sidebar](https://vgwort.wikimannia.org/MediaWiki:Sidebar) as described on [MediaWiki](https://www.mediawiki.org/wiki/Skin:Wima#Use).
**Note 3:** Change $wgDefaultSkin = 'vector'; into $wgDefaultSkin = 'vectorad'; in Localsettings.php or alter the skin in your preferences.

As documented [here](https://www.mediawiki.org/wiki/Skin:Wima), all skins are running here:
* https://vgwort.wikimannia.org/index.php?title=Special:Random&useskin=wima
* https://vgwort.wikimannia.org/index.php?title=Special:Random&useskin=vectorad
* https://vgwort.wikimannia.org/index.php?title=Special:Random&useskin=colognebanner
and they are doing well.

The settings in the LocalSettings.php of the demo example are:
$wgTopBannerCode = '&lt;a title="Uhren-Wiki" href="https://www.uhren-wiki.net"> &lt;img src="https://wikimannia.org/skins/werbung/Werbung_-_Oben.jpg" width="728" height="90" alt="Werbung - Oben" /> &lt;/a>';
$wgTopBannerStyle = 'text-align:center;border:1px solid red;';

$wgBottomBannerCode = '&lt;a title="Uhren-Wiki" href="https://www.uhren-wiki.net"> &lt;img src="https://wikimannia.org/skins/werbung/Werbung_-_Unten.jpg" width="728" height="90" alt="Werbung - Unten" /> &lt;/a>';
$wgBottomBannerStyle = 'text-align:center;border:1px solid blue;';

$wgAdSidebarTopType = 'advertising';
$wgAdSidebarBottomType = 'advertising';

$wgAdSidebarTopCode = '&lt;a title="Schwarzbuch Wikipedia" href="https://at.wikimannia.org/Schwarzbuch_Wikipedia"> &lt;img alt="Schwarzbuch_Wikipedia.jpg" src="https://commons.wikimannia.org/images/thumb/Schwarzbuch_Wikipedia.jpg/150px-Schwarzbuch_Wikipedia.jpg" /> &lt;/a> &lt;p> &lt;b>Schwarzbuch Wikipedia&lt;/b> &lt;/p> &lt;p class="small">Mobbing, Diffamierung und Falsch&shy;information in der Online-Enzyklo&shy;pädie, und was jetzt da&shy;gegen getan werden muss.&lt;/span> &lt;/p> &lt;p>Im Februar 2020 im &lt;i>Zeit&shy;geist-Verlag&lt;/i> erschienen.&lt;/p>';
$wgAdSidebarBottomCode = '&lt;a title="Manuscriptum Verlag" target="_blank" href="https://www.manuscriptum.de/autoren/l/lassahn-bernhard/frau-ohne-welt-3.html"> &lt;img alt="Bernhard_Lassahn_-_Frau_ohne_Welt_-_Teil_3_-_Der_Krieg_gegen_die_Zukunft.jpg" src="https://commons.wikimannia.org/images/thumb/Bernhard_Lassahn_-_Frau_ohne_Welt_-_Teil_3_-_Der_Krieg_gegen_die_Zukunft.jpg/145px-Bernhard_Lassahn_-_Frau_ohne_Welt_-_Teil_3_-_Der_Krieg_gegen_die_Zukunft.jpg" /> &lt;/a> &lt;p> &lt;b>Frau ohne Welt&lt;/b> – Der Krieg gegen die Zukunft.&lt;/p> &lt;p class="small"> &lt;a href="https:de.wikimannia.org/Bernhard_Lassahn">Bernhard Lassahn&lt;/a> gibt mit trotzigem Humor einen Lage&shy;bericht, der aufzeigt, was der vierzig&shy;jährige Krieg an&shy;ge&shy;richtet hat. Zwischen den Geschlechtern, zwischen den Gene&shy;rationen. Die Bilanz könnte kaum bitterer sein. Und doch bleibt Lassahn zu&shy;ver&shy;sichtlich, dass die Welt nicht unter&shy;gehen wird, denn „the only engine of survival“ bleibt weiterhin die Liebe.&lt;/p> &lt;p class="small">Frauen, liebt Männer! Männer, liebt Frauen!&lt;/p> &lt;p>Im Februar 2020 bei &lt;i>Manuscriptum&lt;/i> erschienen.&lt;/p>';

# Age Classification button
$wgAgeClassificationButton = true;
$wgAgeClassificationButtonURL = "www.altersklassifizierung.de/";
$wgAgeClassificationButtonIMG = "yourdomain/skins/fsm-aks148.png";

# Donation button (ie., not set in that example)
$wgDonationButton = true;
$wgDonationButtonURL = 'yourdomain/spende/spende.php?s=';
$wgDonationButtonIMG = $wgServer.'/images/Donate_Button.gif';

# Facebook button (ie., not set in that example)
$wgFacebookButton = true;
$wgFacebookButtonURL = 'www.facebook.com/pages/YourPage/xxxxxxxxxxxxxxx';
$wgFacebookButtonIMG = 'yourdomain/images/Logo-Facebook.png';

**Comment by jdlrobson** [comment]
I have read, but with no references to any of these config variables in the code in this repo I think either your readme is outdated or is omitting a crucial part of the install process e.g. a required extension. Perhaps you are using hooks in your LocalSettings ?

For example, the only references to wgFacebookButton are in the README:
https://github.com/WikiMANNia/MediaWiki-Skins-with-Advertisements/search?q=wgFacebookButton
https://github.com/WikiMANNia/MediaWiki-Skins-with-Advertisements/search?q=FacebookButton

Background: I am trying to understand what you are doing here, as I'm pretty sure you can achieve everything you are doing here with the existing skins (see https://www.mediawiki.org/wiki/Advertising). We shouldn't have to fork skins to run adverts, so as one of the Vector maintainers I'd like to update Vector (and the other skins) themselves to provide this capability if it is indeed missing.

Note: https://www.mediawiki.org/wiki/Skin:Wima (and perhaps the others) are outdated. There is no Wima folder or skin in the current state of the repo which is adding to my confusion.

**Comment by WikiMANNia** [comment]
#1
MediaWiki offers better formatting and I documented all references to all config variables on detail there:
https://www.mediawiki.org/wiki/Skin:VectorAd#wgTopBannerCode

#2
I do not use any hook in the localsettings.php. Just 
1. download your package [here](https://github.com/WikiMANNia/MediaWiki-Skins-with-Advertisements/releases/tag/1.35.0-va) and install it as you used to install a skin
2. then add the requiered global varibales in localsettings.php.
3. Place "*AD1" and "*AD2" into your Mediawiki:Sidebar file.

#3
I tried to have some ads on my wiki but did not find an easy way to do it. I found no other way to place the ads in the sidebar at my choice. I found no way to do it using hooks. If you have a better idea, I am glad to her it.

#4
Switching the branch you will find everything, i.e. this:
https://github.com/WikiMANNia/MediaWiki-Skins-with-Advertisements/tree/REL1_35-wima

**Comment by jdlrobson** [comment]
Ah.. okay so it seems your current `master` doesn't work, but the REL1_35 branch does.  Perhaps the relationship between branches could be mentioned in the README (or even better synced with REL1_35 to have a working master branch)?

**Comment by WikiMANNia** [comment]
"master" contains the original skins monobooks, cologneblue and vector.

Then EACH skin gets for EACH revision its own branch, in the next step all relevant variables are renamed and finally I put the same hack into each of them, offering this as a release for download.

EACH skin for EACH revision has its own release for download. "master" has not.

By the way, it is EASY to SEE that "master" has folders named monobooks, cologneblue and vector, but NOT wima, colognebanner or vectorad.

**Comment by jdlrobson** [comment]
Sure I understand that now, but that was not at all obvious and very confusing. I'm sure somebody else would make the same mistake.

**Comment by WikiMANNia** [comment]
I don't think so. Just download an archive from the [release section](https://github.com/WikiMANNia/MediaWiki-Skins-with-Advertisements/releases) and that's it!

Have a happy new year!

**Comment by jdlrobson** [comment]
When I encounter a `master` branch I expect to get something that reflects the readme. The fact that it doesn't is very unconventional.

That aside, from what I can see, it's possible to replicate exactly what you are doing with a couple of hooks much more elegantly. I'll share something in the new year.

**Comment by WikiMANNia** [comment]
Very kind! It is my first piece for MediaWiki.
