### ISSUE TITLE
Consider using SiteNoticeAfter hook instead of getSitenoticeOrAdvertisementBox

### ISSUE THREAD

**Issue by jdlrobson** [WikiMANNia/MediaWiki-Skins-with-Advertisements#2]
The hook at https://www.mediawiki.org/wiki/Manual:Hooks/SiteNoticeAfter allows you to modify the site notice for /any/ skin. This allows you to add adverts for any skin without having to duplicate the entire skin. In the long term, from what I can see your advert configuration could be used for any skin with a bit of generalization - which would be super cool to see and very helpful for all the mediawiki maintainers not using one of these 4 skins! 

I believe you can achieve the same impact by using the existing SiteNoticeAfter hook. It allows you to modify the site notice for any skins:

Sample code based on current state of Wima:
```
$wgHooks['SiteNoticeAfter'] = function ( &$html, $skin ) { {
		global $wgTopBannerCode;
		$issetSitenoticeBox    = $html === '';
		$issetAdvertisementBox = isset($wgTopBannerCode);

		if ($issetSitenoticeBox && $issetAdvertisementBox) {
			if ( rand(0, 1) ) {
				$html = AdvertController::getSitenoticeBox();
			} else {
				$html = AdvertController::getAdvertisementBoxOben();
			}
		} elseif ($issetSitenoticeBox) {
			$html = AdvertController::getSitenoticeBox();
		} elseif ($issetAdvertisementBox) {
			$html = AdvertController::getAdvertisementBoxOben();
		}

	}
};

```

There are similar hooks that could be used to get adverts in the side bar and footer, but probably best to think of them one at a time?

**Comment by WikiMANNia** [comment]
Great! I am not so in with Hooks and there are so many… I didn't know about 'SiteNoticeAfter' …

The other task to deal with is to find the "AD1" and "AD2" marker.

My this work?

	public static function onSkinBuildSidebar( Skin $skin, array &$sidebar ) {
		global $wgAdSidebarTopCode, $wgAdSidebarBottomCode;
		global $wgAdSidebarTopType, $wgAdSidebarBottomType;

		$skinname = $skin->getSkinName()
		$output = $skin->getOutput();
		$output->addModuleStyles( 'ext.countingmarker.' . $skinname );

		if ( !empty $wgAdSidebarTopCode ) ) {
			$myEntry = [
					   'text'   => $wgAdSidebarTopCode,
					   'href'   => '#',
					   'id'     => 'ad1',
					   'active' => ''
				   ];

			$sidebar['AD1'] = [ $myEntry ];
		} else {
			unset $sidebar['AD1'];
		}
		if ( !empty $wgAdSidebarBottomCode ) ) {
			$myEntry = [
					   'text'   => $wgAdSidebarBottomCode,
					   'href'   => '#',
					   'id'     => 'ad2',
					   'active' => ''
				   ];

			$sidebar['AD2'] = [ $myEntry ];
		} else {
			unset $sidebar['AD2'];
		}
	}

**Comment by WikiMANNia** [comment]
This seems to work!

$wgHooks['SiteNoticeAfter'] = function ( &$html, $skin ) { {
		global $wgTopBannerCode;
		$issetSitenoticeBox    = !empty( $html );
		$issetAdvertisementBox = !empty( $wgTopBannerCode );

		if ($issetSitenoticeBox && $issetAdvertisementBox) {
			if ( rand(0, 1) ) {
	//			$html = AdvertController::getSitenoticeBox();
			} else {
				$html = AdvertController::getAdvertisementBoxOben();
			}
		} elseif ($issetSitenoticeBox) {
	//		$html = AdvertController::getSitenoticeBox();
		} elseif ($issetAdvertisementBox) {
			$html = AdvertController::getAdvertisementBoxOben();
		}

	}
};

**Comment by jdlrobson** [comment]
yeh! You may want to check the skin name if you want to do different things for different skins! Note hooks will run on /all/ skins.

To skip the LocalSettings.php part you can register the hook in skin.json using Hooks in your skin.json by referencing the class and function like in this example:
https://github.com/wikimedia/Vector/blob/master/skin.json#L64

hope that helps?

Longer term it might make sense to turn this into an extension and put it under  https://www.mediawiki.org/wiki/Category:Advertising_extensions but converting skin to extension later should be straightforward.

**Comment by WikiMANNia** [comment]
Please don't tell me things that are so obvious. It may be just off in theory to do it all with hooks and in extensions, but in practice I only get SOME things sorted out with hooks and extensions and there are MANY small and dirty details left over for which no solutions can be found.
This is exactly why I had decided to go the route of hooking the skins directly, because then I can tweak everything to fit.
I have now created three extensions, but I am only 85-90% satisfied with the result. In addition, I have then instead of ONE hooked and aufgeortem skin now THREE extensions. What now in turn again leads to administration and maintenance effort. I have looked around a bit, there are functions and hooks listed out and with each new Mediawiki version I would then have to actively maintain these THREE extensions. So exactly I do not see the advantage.

**Comment by WikiMANNia** [comment]
Hi, the Hook SiteNoticeAfter works fine, but I can not find a way to the markers AD1 and AD2 into translated title "advertising", "event", "hint". :-(

**Comment by WikiMANNia** [comment]
Resolved! See:
- https://www.mediawiki.org/wiki/Extension:WimaAdvertising
- https://github.com/WikiMANNia/MediaWiki-Extension-WimaAdvertising/
