### ISSUE TITLE
VectorAd appears to break navigation tabs

### ISSUE THREAD

**Issue by DerfJagged** [WikiMANNia/MediaWiki-Skins-with-Advertisements#3]
Hello! I had downloaded the 1.35.0 release of VectorAd and installed it on my 1.35.0 MediaWiki and added the required variable in LocalSettings.php. However, it appears that the navigation tabs appear to missing and their contents are spilled on the page.
See here: https://consolemods.org/wiki/Main_Page

I disabled my custom CSS and the issue remained after a cache hard reset. 

Perhaps I am missing something, but the three demo sites also look identical. They should be three different skins, correct?
https://vgwort.wikimannia.org/index.php?title=Special:Random&useskin=wima
https://vgwort.wikimannia.org/index.php?title=Special:Random&useskin=vectorad
https://vgwort.wikimannia.org/index.php?title=Special:Random&useskin=colognebanner

**Comment by WikiMANNia** [comment]
It really looks strange. :-(

MediaWiki-Skins-with-Advertisements is no longer supported, please use

WikiMANNia/MediaWiki-Extension-WimaAdvertising

It does the same job but even better! ;-)

See Extension:WimaAdvertising (https://www.mediawiki.org/wiki/Extension:WimaAdvertising)

**Comment by DerfJagged** [comment]
Ah, I see. I suppose a note should be made here to warn people it's not supported: https://www.mediawiki.org/wiki/Skin:VectorAd

I'll use that, thank you!

**Comment by WikiMANNia** [comment]
See in the README:

> IMPORTANT NOTE: This project is **abandoned** in favor of WimaAdvertising and DonateButton.
