### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by jdlrobson** [WikiMANNia/MediaWiki-Skins-with-Advertisements#4]
There are a few issues with the latest 1.39 release. I'm not sure if this extension is continuing to being maintained

One issue is the use of the legacy feature:
See https://www.mediawiki.org/wiki/Manual:ResourceLoaderSkinModule#For_skins_deprecating_the_legacy_feature for directions on how to fix this.

Happy to flag more issues once I know on the status of this extension.

**Comment by WikiMANNia** [comment]
Please read on the Mainpage:

> "IMPORTANT NOTE: This project is abandoned in favor of [WimaAdvertising](https://github.com/WikiMANNia/MediaWiki-Extension-WimaAdvertising) and [DonateButton](https://github.com/WikiMANNia/MediaWiki-Extension-DonateButton)."

https://github.com/WikiMANNia/MediaWiki-Skins-with-Advertisements/blob/master/README.md

**Comment by jdlrobson** [comment]
Could you mark the repository as archived (read only)?
